;;; tests/create_test.el --- Creation support tests -*- lexical-binding: t; no-byte-compile: t; -*-
(require 'auth-source-sops "./auth-source-sops.el")

(ert-deftest auth-source-sops-create-new-test ()
  "Verify that creating a new entry works."
  (let ((set-calls 0)
        (last-payload nil))
    (cl-letf* (((symbol-function 'auth-source-sops--get-raw-structure) (lambda () nil))
               ((symbol-function 'read-string) (lambda (_prompt &optional _init _hist default) (or default "testuser")))
               ((symbol-function 'read-passwd) (lambda (_prompt) "testpass"))
               ((symbol-function 'auth-source-sops-get-string-from-file) (lambda (_) "fake-key"))
               ((symbol-function 'call-process)
                (lambda (_exe _infile destination _display &rest args)
                  (if (member "set" args)
                      (progn
                        (setq set-calls (1+ set-calls))
                        (setq last-payload (nth 2 args))
                        0)
                    0))))
      
      (let ((auth-source-sops-file "/fake/path.yaml")
            (auth-source-sops-search-method :incremental)
            (auth-source-sops--raw-cache nil))
        (auth-source-sops-enable)
        (let ((results (auth-source-search :host "newhost" :create t)))
          (should (= (length results) 1))
          (should (equal (plist-get (car results) :host) "newhost"))
          (should (equal (funcall (plist-get (car results) :secret)) "testpass"))
          (should (= set-calls 1))
          ;; Payload should be a JSON array containing one entry
          (should (string-match-p "testuser" last-payload))
          (should (string-match-p "testpass" last-payload)))))))

(ert-deftest auth-source-sops-create-existing-test ()
  "Verify that adding an entry to an existing host works."
  (let ((set-calls 0)
        (last-payload nil))
    (cl-letf* (((symbol-function 'auth-source-sops--get-raw-structure) 
                (lambda () '(("host1" . "enc"))))
               ((symbol-function 'auth-source-sops--extract-branch)
                (lambda (_key) "user: u1\nsecret: p1"))
               ((symbol-function 'auth-source-sops-parse)
                (lambda (_f _c) '((user . "u1") (secret . "p1"))))
               ((symbol-function 'read-string) (lambda (&rest _) "u2"))
               ((symbol-function 'read-passwd) (lambda (_p) "p2"))
               ((symbol-function 'auth-source-sops-get-string-from-file) (lambda (_) "fake-key"))
               ((symbol-function 'call-process)
                (lambda (_exe _in _dest _disp &rest args)
                  (if (member "set" args)
                      (progn
                        (setq set-calls (1+ set-calls))
                        (setq last-payload (nth 2 args))
                        0)
                    0))))
      (let ((auth-source-sops-file "/fake/path.yaml")
            (auth-source-sops-search-method :incremental)
            (auth-source-sops--raw-cache nil))
        (auth-source-sops-enable)
        (let ((results (auth-source-search :host "host1" :user "u2" :create t)))
          (should (= (length results) 1))
          (should (= set-calls 1))
          ;; Payload should contain both u1 and u2
          (should (string-match-p "u1" last-payload))
          (should (string-match-p "u2" last-payload)))))))

(provide 'create-test)
