(provide 'yaml)

(defun yaml-parse-string (string &rest args)
  "Mock yaml-parse-string for testing."
  (cond
   ((string-match-p "repro-machine" string)
    '(("repro-machine" . [ (("machine" . "machine.example.com") ("password" . "secure")) ])))
   ((string-match-p "repro-sudo" string)
    '(("repro-sudo" . [ (("host" . "sudo-host") ("port" . "sudo") ("user" . "root") ("password" . "sudo-password")) ])))
   ((string-match-p "me@email.com" string)
    '(("me@email.com@complex-host:99" . [ (("password" . 99)) ])))
   ((string-match-p "multiple-users" string)
    '(("multiple-users" . [ (("user" . "user1") ("password" . "pass1"))
                            (("user" . "user2") ("password" . "pass2")) ])))
   ((string-match-p "malformed" string)
    (error "YAML parsing error"))
   (t
    '(("github" . "1")
      ("github.com" . "2")
      ("example@github.com" . "3")
      ("github.com:22" . "4")
      ("example@github.com:22" . "5")
      ("api.github.com" . [ (("user" . "apikey") ("secret" . "6")) ])
      ("origin@api.github.com" . [ (("user" . "override") ("secret" . "7")) ])
      ("nested" . [ (("user" . "example") ("secret" . "8") ("test" . (("deep" . 1)))) ])
      ("me@email.com@complex-host:123" . "99")
    ))))
